//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Report.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        public int sq_relatorio { get; set; }
        public short sq_modulo { get; set; }
        public string nm_arquivo { get; set; }
        public byte[] nmConteudo { get; set; }
        public string nmPalavraChave { get; set; }
    }
}
