//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanFiles.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInfo
    {
        public int Id { get; set; }
        public string Method { get; set; }
        public short NumberOfLines { get; set; }
        public bool HasComment { get; set; }
    
        public virtual FileType FileType { get; set; }
    }
}
